##**실습 (Assignment 7)**
  - 행렬 방정식 풀기
      - 다음 행렬 방정식을 'Linear Regression'을 이용해 풀어보자
         * 적당한 learning rate를 찾아 1000 epoch 정도 계산해본다
      - Hint: y = wx꼴로 변환해본다
        * Ax=B에서는 x가 미지수이지만, y=wx에서는 w가 미지수임에 주의
        *linear model에서 b를 없애기 위해서 nn.Linear()사용법을 검색하본다
\
$$Ax=B$$
$$A =\left[\begin{array}{rr} 
0&1\\
1&1\\
2&1\\
3&1
\end{array}\right]$$
$$B =\left[\begin{array}{r} 
-1\\
0.2\\
0.9\\
2.1
\end{array}\right]$$

In [ ]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as func
import torch.optim as opt

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
torch.manual_seed(1)

In [ ]:
tensorA = torch.FloatTensor([[0,1],[1,1],[2,1],[3,1]])
tensorB = torch.FloatTensor([[-1],[0.2],[0.9],[2.1]])
#print(tensorA)

In [ ]:
model = nn.Linear(2,1,bias=False)

In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.3643, -0.3121]], requires_grad=True)]


In [ ]:
y_hypo = model(tensorA)
print(y_hypo)

tensor([[-0.3121],
        [ 0.0522],
        [ 0.4166],
        [ 0.7809]], grad_fn=<MmBackward>)


In [ ]:
cost = func.mse_loss(y_hypo, tensorA)
print(cost)

tensor(1.4294, grad_fn=<MseLossBackward>)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Using a target size (torch.Size([4, 2])) that is different to the input size (torch.Size([4, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  """Entry point for launching an IPython kernel.


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-2)

In [ ]:
EpochNum = 10000
for epoch in range(EpochNum+1):
   y_hypo = model(tensorA)
   cost = func.mse_loss(y_hypo, tensorB)

   optimizer.zero_grad()
   cost.backward()
   optimizer.step()

   if epoch % 100 == 0:
     print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, EpochNum, cost.item()))
print(list(model.parameters()))

Epoch    0/10000 Cost: 0.617162
Epoch  100/10000 Cost: 0.077246
Epoch  200/10000 Cost: 0.032132
Epoch  300/10000 Cost: 0.018453
Epoch  400/10000 Cost: 0.014305
Epoch  500/10000 Cost: 0.013047
Epoch  600/10000 Cost: 0.012666
Epoch  700/10000 Cost: 0.012550
Epoch  800/10000 Cost: 0.012515
Epoch  900/10000 Cost: 0.012505
Epoch 1000/10000 Cost: 0.012501
Epoch 1100/10000 Cost: 0.012500
Epoch 1200/10000 Cost: 0.012500
Epoch 1300/10000 Cost: 0.012500
Epoch 1400/10000 Cost: 0.012500
Epoch 1500/10000 Cost: 0.012500
Epoch 1600/10000 Cost: 0.012500
Epoch 1700/10000 Cost: 0.012500
Epoch 1800/10000 Cost: 0.012500
Epoch 1900/10000 Cost: 0.012500
Epoch 2000/10000 Cost: 0.012500
Epoch 2100/10000 Cost: 0.012500
Epoch 2200/10000 Cost: 0.012500
Epoch 2300/10000 Cost: 0.012500
Epoch 2400/10000 Cost: 0.012500
Epoch 2500/10000 Cost: 0.012500
Epoch 2600/10000 Cost: 0.012500
Epoch 2700/10000 Cost: 0.012500
Epoch 2800/10000 Cost: 0.012500
Epoch 2900/10000 Cost: 0.012500
Epoch 3000/10000 Cost: 0.012500
Epoch 31

In [ ]:
tensorx=torch.FloatTensor([[1.0000],[-0.9500]])
print(tensorx)
print(tensorA)
print(torch.matmul(tensorA,tensorx))

tensor([[ 1.0000],
        [-0.9500]])
tensor([[0., 1.],
        [1., 1.],
        [2., 1.],
        [3., 1.]])
tensor([[-0.9500],
        [ 0.0500],
        [ 1.0500],
        [ 2.0500]])
